### ISSUE TITLE
dlg_VC700/dlg_ESXI700

### ISSUE THREAD

**Issue by bmilcs** [Texiwill/aac-lib#4]
/tmp/vsm.bmilcs/depot.vmware.     [ <=>                                              ]  98.51K  --.-KB/s    in 0.05s
Existing ESXI700 in 

/tmp/vsm.bmilcs/depot.vmware.     [ <=>                                              ]  92.85K  --.-KB/s    in 0.06s
Existing VC700 in 

I cannot seem to download v7 of ESXI or VC using the script. I repeatedly get this error, and yet, each is empty. It does work w/ other v7 enterprise/essentials, but unfortunately, not the core apps I need.

**Comment by bmilcs** [comment]
I've tried deleting my saved .vmrc, tmp/ and those folders mentioned above, but it repeats.

**Comment by Texiwill** [comment]
Hello,

If you are not entitled to the download then you cannot download the bits associated with the package. In order to tell if the user you are using has an entitlement, go into the package. If the package files are written to the screen in grey then you do not have access. If you are entitled either as a vExpert or an entitlement inside My VMware, then I will need to know which one, the output of the script (the header part is fairly important), and the arguments you are using to call vsm.sh. Please send all support requests to the email address mentioned in the README.
